/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    ArticleCard: typeof import('./src/components/article/ArticleCard.vue')['default']
    CategoryCard: typeof import('./src/components/sidebar/CategoryCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PopularPosts: typeof import('./src/components/sidebar/PopularPosts.vue')['default']
    ProfileCard: typeof import('./src/components/sidebar/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagCard: typeof import('./src/components/sidebar/TagCard.vue')['default']
  }
}
